### ISSUE TITLE
Error when last file open is an image

### ISSUE THREAD

**Issue by MSchlieper** [benmatselby/sublime-phpcs#100]
I'm using PHPCS with ST3 3056 which has the ability to display images (as images and not just the raw binary data).
If I close ST3 and the last file open was such an image, I have the following output in my console when restarting ST3 and "auto-reopening" this recent image:

Traceback (most recent call last):
  File "/Applications/MyApplications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "phpcs in /Users/groucho/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 91, in plugin_loaded
  File "phpcs in /Users/groucho/Library/Application Support/Sublime Text 3/Installed Packages/Phpcs.sublime-package", line 59, in load
AttributeError: 'NoneType' object has no attribute 'settings'

**Comment by benmatselby** [comment]
@MSchlieper @brodkin Should be fixed now in 6.6.3.
