### ISSUE TITLE
Not able to run any of the command

### ISSUE THREAD

**Issue by hemangajmera** [benmatselby/sublime-phpcs#138]
I am using xampp and composer. Here is how my settings looks like
```json
{
	"php_cs_fixer_executable_path":"C:\\Users\\ajmerah\\AppData\\Roaming\\Composer\\vendor\\bin",
	"php_cs_fixer_executable_path":"C:\\Users\\ajmerah\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat",
	"phpcbf_executable_path":"C:\\Users\\ajmerah\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcbf.bat",
	"phpcs_commands_to_php_prefix": ["Fixer"],
	"phpcs_executable_path":"C:\\Users\\ajmerah\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcs.bat",
	"phpcs_php_path":"c:\\xampp\\php",
	"phpcs_php_prefix_path":"c:\\xampp\\php\\php.exe",
	"phpmd_executable_path":"C:\\Users\\ajmerah\\AppData\\Roaming\\Composer\\vendor\\bin\\phpmd.bat",
}
```

This is the error I am getting

Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 649, in run
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 465, in run
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 421, in execute
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 424, in parse_report
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 173, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
PermissionError: [WinError 5] Access is denied
```

**Comment by benmatselby** [comment]
Can you please capture the commands trying to be run in the console and past in here please.

**Comment by benmatselby** [comment]
Hi @hemangajmera - Any luck getting the information from the console?

**Comment by hemangajmera** [comment]
This is complete console

'''
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/ajmerah/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/ajmerah/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/ajmerah/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 3.09945
startup time: 3.24645
first paint time: 3.25545
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Phpcs.phpcs
reloading plugin XmlDocs.XmlDocs
plugins loaded
Package Control: No updated packages
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 649, in run
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 465, in run
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 143, in get_errors
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 421, in execute
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 424, in parse_report
  File "phpcs in C:\Users\ajmerah\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 173, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
PermissionError: [WinError 5] Access is denied
'''

**Comment by benmatselby** [comment]
Hi @hemangajmera 

I'm really sorry, I don't have access to a windows machine, so cannot really help here. Have you googled "Python WinError 5" to see what that suggests?

I would expect if this was a bug in the plugin for more people to be raising this.

**Comment by daniellz** [comment]
You must start Sublime as Admin. This help in my case.

**Comment by benmatselby** [comment]
Closing as there seems to be a workaround

**Comment by cmarabate** [comment]
I have the same exact issue but running Sublime Text as Administrator doesn't make a difference for me.
