### ISSUE TITLE
Sublime text on linux - AttributeError

### ISSUE THREAD

**Issue by isalcedo** [benmatselby/sublime-phpcs#182]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "phpcs in /home/isalcedo/.config/sublime-text-3/Installed Packages/Phpcs.sublime-package", line 661, in run
  File "phpcs in /home/isalcedo/.config/sublime-text-3/Installed Packages/Phpcs.sublime-package", line 479, in run
  File "phpcs in /home/isalcedo/.config/sublime-text-3/Installed Packages/Phpcs.sublime-package", line 149, in get_errors
  File "phpcs in /home/isalcedo/.config/sublime-text-3/Installed Packages/Phpcs.sublime-package", line 215, in execute
AttributeError: 'str' object has no attribute 'items'

**Comment by benmatselby** [comment]
Hi @isalcedo Could you provide some context please. What config you have, what you are trying to do etc please ?

**Comment by isalcedo** [comment]
Sorry, I don't remember when I wrote this, maybe was automatic. I'll check for the things that are you asking for.

**Comment by benmatselby** [comment]
@isalcedo Closing for now, if you see the issue again, please provide the config, and some context
