### ISSUE TITLE
Doesn't work on my windows 10

### ISSUE THREAD

**Issue by jeraldpunx** [benmatselby/sublime-phpcs#190]
Error after executing SNIFF THIS FILE

```
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 661, in run
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 479, in run
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 149, in get_errors
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 231, in execute
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 234, in parse_report
  File "C:\Users\JeraldPunx\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package\phpcs.py", line 176, in shell_out
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jeraldpunx** [comment]
This is my config, 
![image](https://user-images.githubusercontent.com/5249781/56893748-5be77b80-6ab6-11e9-95c6-ec57f8d4ac90.png)



![image](https://user-images.githubusercontent.com/5249781/56893813-918c6480-6ab6-11e9-9417-cfde30660784.png)

**Comment by benjivm** [comment]
On Windows you need to reference the `.bat` files in your config. Also if those are in your PATH you can drop the path, e.g., in my config I have:

```json
"php_cs_fixer_executable_path": "php-cs-fixer.bat",
```

**Comment by Micu22** [comment]
I have the same issue.
This is not working:
`{
	"show_debug": true,
        //phpcs.bat not working, AND phpcs (without .bat) not working
	"phpcs_executable_path": "/c/Users/micha/AppData/Roaming/Composer/vendor/bin/phpcs.bat",
	"phpcs_additional_args": {
		"--standard": "WordPress",
		"-n": ""
	}
}`
nor this:
`{
	"show_debug": true,
        //phpcs.bat not working, AND phpcs (without .bat) not working
	"phpcs_executable_path": "/Users/micha/AppData/Roaming/Composer/vendor/bin/phpcs",
	"phpcs_additional_args": {
		"--standard": "WordPress",
		"-n": ""
	}
}`
Using phpcs from command line works without problems.

**Comment by pablo-sg-pacheco** [comment]
Doesn't work for me too, same problem :(

**Comment by valentinoPereira** [comment]
I'm facing the same issue..

**Comment by benmatselby** [comment]
Hey folks. Apologies. I don't use PHP or Sublime anymore (Nor do I have a Windows machine), so realistically I'm not going to be able to get to look this. I think there are other php linters in the Sublime ecosystem, hopefully they meet your needs.

**Comment by code05-hello** [comment]
Hi, I have made it working after few minutes of R&D phew
Step1 is to download all the .phar files, and move them to your /usr/local/bin folder, and make sure, you give them 777 permission to these files.

After that open a new terminal session, and try to type phpcs.phar, and if it works, then do following as below : 
Below is the settings you have to use on sublime-text 4 user settings file of the phpcs package.

```
If it does not work, then add below settings
First download all the .phar from the websites, and then in the settings 

{
    "phpcs_php_path": "/usr/local/opt/php@7.4/bin/php",
    "phpcs_executable_path": "/usr/local/bin/phpcs.phar",
    "phpcbf_executable_path":"/usr/local/bin/phpcbf.phar",
    "phpmd_executable_path":"/usr/local/bin/phpmd.phar",
}

**Comment by benmatselby** [comment]
Hey folks. Closing this issue down with the fix from @code05-hello
