### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by christoferd** [benmatselby/sublime-phpcs#78]
Hi Ben,

Got an error with your Sublime Text 2 plugin. I just installed it and was testing to see what happens when I just type junk into php... didn't notice anything so I turned on debug and this is what I saw...

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 272, in is_enabled_
  File ".\phpcs.py", line 605, in is_enabled
  File ".\phpcs.py", line 528, in should_execute
TypeError: argument of type 'NoneType' is not iterable

Cheerio

**Comment by temple** [comment]
Hi Ben, I've got similar error

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 337, in run_
  File "./phpcs.py", line 670, in run
  File "./phpcs.py", line 501, in fix_standards_errors
  File "./phpcs.py", line 139, in get_errors
  File "./phpcs.py", line 246, in execute
TypeError: argument of type 'NoneType' is not iterable
```

When I right-click on any file or folder of my SF2 project and select PHP Code Sniffer _Fix this file/directory (php cs fixer)_

I'm using Sublime Text 2.0.2
And installed all requirements for sublime-phpcs but facebook/pfff

I've got the phar executable paths correctly specified at /~/.config/sublime-text-2/Packages/Phpcs/phpcs.sublime-settings

Moreover, phpcs show any option disabled when I right-click on a php file text inside my project.

What should I do?

**Comment by temple** [comment]
Hi again Ben,
I think I've solved previous reported errors.

But in other hand, I've got an OS permissions error when I try to fix with CS Fixer a php file, using this sublime plugin

> [Phpcs] /var/www/myproject/php-cs-fixer.phar fix /var/www/myproject/src/Main/Components/Comment/Model/Interfaces/CommentCollectionInteface.php --verbose
[Phpcs] /var/www/myproject/php-cs-fixer.phar fix /var/www/myproject/src/Main/Components/Comment/Model/Interfaces/CommentCollectionInteface.php --verbose
[Phpcs] cwd: /home/myusername
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./phpcs.py", line 657, in run
  File "./phpcs.py", line 501, in fix_standards_errors
  File "./phpcs.py", line 139, in get_errors
  File "./phpcs.py", line 269, in execute
  File "./phpcs.py", line 272, in parse_report
  File "./phpcs.py", line 169, in shell_out
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 13] S’ha denegat el permís //AUTHOR POST: This means Forbidden in catalan language

Any suggestion?

**Comment by temple** [comment]
I seems that the error comes near this last line of code from 
**~/.config/sublime-text-2/Packages/Phpcs/phpcs.py**
corresponding the method _shell_out(self, cmd):_
starting at line 161
```python
        """
        Fixes the fact that PHP_CodeSniffer now caches the reports to cwd()
         - http://pear.php.net/package/PHP_CodeSniffer/download/1.5.0
         - https://github.com/benmatselby/sublime-phpcs/issues/68
        """
        home = expanduser("~")
        debug_message("cwd: " + home)

        proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, startupinfo=info, cwd=home)
```

**Comment by benmatselby** [comment]
@temple Have you seen this section in the readme?

https://github.com/benmatselby/sublime-phpcs#what-do-i-do-when-i-get-oserror-errno-13-permission-denied
